# Generated by Django 4.2.3 on 2025-12-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_livenews', '0004_livenews_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='livenews',
            name='fact_check_verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livenews',
            name='is_fact_check_article',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='livenews',
            name='source_credibility',
            field=models.CharField(default='UNKNOWN', max_length=50),
        ),
        migrations.AddField(
            model_name='livenews',
            name='source_domain',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
